#!/usr/bin/env python3
"""Derived recurrence tally for meta/attribution-table.md.

The "Recurrence ledger summary" in attribution-table.md used to be hand-maintained per run,
which drifted (every 2026-07-01 run independently flagged "a full re-tally is owed") and
guaranteed merge conflicts between parallel Claude Code sessions. This script makes the
summary DERIVED: it recomputes the whole table from meta/findings-ledger.jsonl (+ proposal
frontmatter under meta/improvement-proposals/) and rewrites the block between the

  <!-- tally:begin ... -->  /  <!-- tally:end -->

markers in meta/attribution-table.md. Nothing outside the markers is touched, so the
human/retro-authored routing tables and narratives are safe.

Usage:
  python meta/tally_ledger.py            # print the generated block to stdout
  python meta/tally_ledger.py --write    # rewrite the marker block in attribution-table.md
  python meta/tally_ledger.py --check    # exit 1 if the block in the file is stale

`meta/regression.py` runs the --check mode, so an applied proposal (or a merged run branch)
that changes the ledger without regenerating the tally fails regression until
`python meta/tally_ledger.py --write` is re-run.
"""

import argparse
import json
import os
import re
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
LEDGER = os.path.join(HERE, "findings-ledger.jsonl")
PROPOSALS = os.path.join(HERE, "improvement-proposals")
TABLE = os.path.join(HERE, "attribution-table.md")

BEGIN_RE = re.compile(r"<!-- tally:begin[^>]*-->")
END_MARK = "<!-- tally:end -->"
BEGIN_MARK = ("<!-- tally:begin — generated by `python meta/tally_ledger.py --write`; "
              "do not hand-edit -->")

# Ledger `source` values, in display order.
SOURCES = ["gate", "editorial", "self-audit", "human-revision", "retro"]
SOURCE_HEADERS = ["gate", "editorial", "self-audit", "human-rev", "retro"]


def _load_ledger():
    records = []
    with open(LEDGER, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def _load_proposals():
    """Map pattern_tag -> [(proposal_id, status_word)], from proposal frontmatter."""
    by_tag = defaultdict(list)
    n_files = 0
    if not os.path.isdir(PROPOSALS):
        return by_tag, 0
    for name in sorted(os.listdir(PROPOSALS)):
        if not re.match(r"\d{4}-\d{2}-\d{2}-.*\.md$", name):
            continue
        n_files += 1
        with open(os.path.join(PROPOSALS, name), "r", encoding="utf-8") as fh:
            text = fh.read()
        m = re.match(r"---\n(.*?)\n---", text, re.DOTALL)
        if not m:
            continue
        fm = m.group(1)
        pid_m = re.search(r"^proposal_id:\s*(\S+)", fm, re.MULTILINE)
        status_m = re.search(r"^status:\s*([A-Za-z-]+)", fm, re.MULTILINE)
        pid = pid_m.group(1) if pid_m else name[:-3]
        status = status_m.group(1) if status_m else "?"
        tags = set(re.findall(r"pattern_tag:\s*([A-Za-z0-9_-]+)", fm))
        for tag in tags:
            by_tag[tag].append((pid, status))
    return by_tag, n_files


def generate():
    records = _load_ledger()
    prop_by_tag, n_props = _load_proposals()

    per_tag = defaultdict(lambda: {"records": 0, "essays": set(),
                                   "by_source": defaultdict(int)})
    untagged = 0
    runs = set()
    for r in records:
        runs.add(r.get("essay_id"))
        tag = r.get("pattern_tag")
        if not tag:
            untagged += 1
            continue
        row = per_tag[tag]
        row["records"] += 1
        row["essays"].add(r.get("essay_id"))
        row["by_source"][r.get("source")] += 1

    lines = [BEGIN_MARK, ""]
    lines.append("| pattern_tag | records | essays | " +
                 " | ".join(SOURCE_HEADERS) + " | proposals |")
    lines.append("|---|---|---|" + "---|" * len(SOURCES) + "---|")
    ordered = sorted(per_tag.items(), key=lambda kv: (-kv[1]["records"], kv[0]))
    for tag, row in ordered:
        props = prop_by_tag.get(tag, [])
        prop_cell = ", ".join("`%s` (%s)" % (pid, status) for pid, status in props) or "—"
        cells = ["`%s`" % tag, str(row["records"]), str(len(row["essays"]))]
        cells += [str(row["by_source"].get(s, 0) or "") if row["by_source"].get(s, 0)
                  else "" for s in SOURCES]
        cells.append(prop_cell)
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    lines.append("Derived from %d ledger records (%d tagged + %d untagged coverage/no-finding "
                 "records) across %d runs, and %d proposal files. Do not hand-edit: regenerate "
                 "with `python meta/tally_ledger.py --write`; `meta/regression.py` fails while "
                 "this block is stale. Proposal statuses come from each proposal file's "
                 "frontmatter (`watch` / `recommended-apply` / `applied` / `escalated`)."
                 % (len(records), len(records) - untagged, untagged, len(runs), n_props))
    lines.append(END_MARK)
    return "\n".join(lines)


def _split_table(text):
    begin = BEGIN_RE.search(text)
    if not begin:
        return None
    end = text.find(END_MARK)
    if end < 0:
        return None
    return text[:begin.start()], text[end + len(END_MARK):]


def main(argv=None):
    p = argparse.ArgumentParser(description="derived recurrence tally")
    mode = p.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = p.parse_args(argv)

    block = generate()
    if not (args.write or args.check):
        print(block)
        return 0

    with open(TABLE, "r", encoding="utf-8") as fh:
        text = fh.read()
    parts = _split_table(text)
    if parts is None:
        print("tally: no <!-- tally:begin --> / <!-- tally:end --> markers in %s" % TABLE,
              file=sys.stderr)
        return 1
    head, tail = parts
    new_text = head + block + tail

    if args.check:
        if new_text != text:
            print("tally: STALE — attribution-table.md tally block does not match the ledger; "
                  "run `python meta/tally_ledger.py --write`", file=sys.stderr)
            return 1
        print("tally: in sync")
        return 0

    if new_text != text:
        with open(TABLE, "w", encoding="utf-8") as fh:
            fh.write(new_text)
        print("tally: rewrote block in %s" % TABLE)
    else:
        print("tally: already in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
